apiVersion: v1
kind: Pod
metadata:
  name: kuard
spec:
  containers:
    - image: 652455772073.dkr.ecr.eu-west-1.amazonaws.com/kubernetes_ur/kuard-amd64:blue
      name: kuard
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
