apiVersion: apps/v1
kind: Deployment
metadata:
  name: ghost
spec:
  replicas: 1
  selector:
    matchLabels:
      run: ghost
  template:
    metadata:
      labels:
        run: ghost
    spec:
      containers:
        - name: ghost
          image: ghost
          command:
            - sh
            - -c
            - cp /ghost-config/ghost-config.js /var/lib/ghost/config.js
              && /usr/local/bin/docker-entrypoint.sh node current/index.js
          volumeMounts:
            - name: config
              mountPath: /ghost-config
      volumes:
        - name: config
          configMap:
            name: ghost-config-mysql
            defaultMode: 420
---
apiVersion: v1
kind: Service
metadata:
  name: ghost
spec:
  selector:
      run: ghost
  ports:
    - port: 2368
      protocol: TCP
      targetPort: 2368