# Deploy parse with required env variables (example only - not secure)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: parse-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: parse-server
  template:
    metadata:
      labels:
        run: parse-server
    spec:
      containers:
        - name: parse-server
          image: 652455772073.dkr.ecr.eu-west-1.amazonaws.com/parse-server:latest
          env:
            - name: PARSE_SERVER_DATABASE_URI
              value: "mongodb://mongo-0.mongo:27017,\
                mongo-1.mongo:27017,mongo-2.mongo:27017/dev?replicaSet=rs0"
            - name: PARSE_SERVER_APPLICATION_ID
              value: my-app-id
            - name: PARSE_SERVER_MASTER_KEY
              value: my-master-key
---
# Configure parse service
apiVersion: v1
kind: Service
metadata:
  name: parse-server
  namespace: default
spec:
  ports:
    - port: 1337
      protocol: TCP
      targetPort: 1337
  selector:
    run: parse-server