apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      name: peer
  clusterIP: None
  selector:
    app: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 3
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:4.0.11-alpine
          command: [sh, -c, source /redis-config/init.sh]
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - mountPath: /redis-config
              name: config
            - mountPath: /redis-data
              name: data
        - name: sentinel
          image: redis:4.0.11-alpine
          command: [sh, -c, source /redis-config-src/sentinel.sh]
          volumeMounts:
            - mountPath: /redis-config-src
              name: config
            - mountPath: /redis-config
              name: data
      volumes:
        - configMap:
            defaultMode: 420
            name: redis-config
          name: config
        - emptyDir:
          name: data